name: ci-tests
on: 
  push:
  pull_request:
    branches:
      - main
    paths:
      - ./**

env:
  AWS_DEFAULT_REGION: 'eu-north-1'
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
        
      # - name: Lint
      #   working-directory: "./"
      #   run: poetry run pylint --recursive=y .

      - name: Pull data and model
        run: pipenv run dvc pull
  
      - name: Run pipline
        env:
          access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
        run: pipenv run dvc exp run evaluate

      - name: Iterative CML setup
        uses: iterative/setup-cml@v1
    
      - name: Create CML report
        env:
          REPO_TOKEN: ${{secrets.SECRET_TOKEN}}
        run: |
          # Add the metrics to the report
          dvc metrics show --show-md >> report.md
          # Add the parameters to the report
          cat dvclive/params.yaml >> report.md
          # Create a report in PR
          cml comment create report.md 


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}







          



